name: Check Release
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
    types: [labeled, unlabeled, opened, edited, synchronize]
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Install Dependencies
        shell: bash
        run: |
          pip install -e .
      - name: Check Release
        uses: ./.github/actions/check-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: jupyter-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist

  enforce-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: enforce-triage-label
        uses: jupyterlab/maintainer-tools/.github/actions/enforce-label@v1

  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Install Dependencies
        shell: bash
        run: |
          pip install -e .
      - name: Populate Release
        id: populate-release
        uses: jupyter-server/jupyter_releaser/.github/actions/populate-release@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          target: https://github.com/arnos-stuff/jupyterlab-purple-wave-theme
          branch: main
          release_url: https://github.com/arnos-stuff/jupyterlab-purple-wave-theme/releases/

      - name: Finalize Release
        id: finalize-release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          PYPI_TOKEN_MAP: ${{ secrets.PYPI_TOKEN_MAP }}
          TWINE_USERNAME: __token__
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        uses: jupyter-server/jupyter-releaser/.github/actions/finalize-release@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target }}
          release_url: ${{ steps.populate-release.outputs.release_url }}

      - name: "** Next Step **"
        if: ${{ success() }}
        run: |
          echo "Verify the final release"
          echo ${{ steps.finalize-release.outputs.release_url }}

      - name: "** Failure Message **"
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:"
          echo ${{ steps.populate-release.outputs.release_url }}
    
