name: Check Release
on: [push]
run-name: ${{ github.actor }} is using jupyterlab releaser

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: jupyter-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
